# Generated by Django 4.2.7 on 2023-12-04 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0003_printer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('document', models.FileField(blank=True, max_length=200, null=True, upload_to='files_to_print')),
                ('no_of_copies', models.IntegerField()),
                ('pages', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('time_expected', models.TimeField()),
                ('is_complete', models.BooleanField(default=False)),
                ('pay_on_collection', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.printer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
