# Generated by Django 4.2.7 on 2023-12-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_alter_order_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="coloured",
            field=models.BooleanField(default=False),
        ),
    ]
