# Generated by Django 4.2.7 on 2023-12-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_order_coloured"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
