# Generated by Django 4.2.7 on 2024-03-09 14:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_order_charge"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="pay_on_collection",
        ),
    ]
