# Generated by Django 4.2.7 on 2024-08-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0007_remove_order_pay_on_collection"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.UUIDField()),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        max_length=200,
                        null=True,
                        upload_to="files_to_print",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="order",
            name="document",
        ),
    ]
