# Generated by Django 4.2.7 on 2024-10-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0009_orderdocument_document_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderdocument",
            name="document_name",
            field=models.CharField(default="P"),
        ),
    ]
