# Generated by Django 4.2.7 on 2023-12-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_wallet_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='transactions',
            field=models.ManyToManyField(blank=True, related_name='is_for', to='wallet.transaction'),
        ),
    ]
