# Generated by Django 4.2.7 on 2023-12-04 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_printer'),
        ('wallet', '0003_alter_wallet_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], default='CREDIT', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='printer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.printer'),
        ),
    ]
