# Generated by Django 4.2.7 on 2023-12-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="time_posted",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
