# Generated by Django 4.2.7 on 2024-03-09 14:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0002_alter_review_time_posted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="time_posted",
        ),
        migrations.AddField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="review",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
