# Generated by Django 4.2.7 on 2023-12-04 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_account_name_alter_user_account_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('description', models.TextField()),
                ('is_open', models.BooleanField(default=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=225)),
                ('average_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('offers_coloured', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
