# Generated by Django 4.2.7 on 2023-12-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_onetimepassword_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="printer",
            name="id_user",
            field=models.IntegerField(unique=True),
        ),
    ]
