# Generated by Django 4.2.7 on 2023-12-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0006_alter_printer_average_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="printer",
            name="coloured_rate",
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name="printer",
            name="uncoloured_rate",
            field=models.IntegerField(default=20),
        ),
    ]
