# Generated by Django 4.2.7 on 2024-03-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0007_printer_coloured_rate_printer_uncoloured_rate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="account_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="account_number",
        ),
        migrations.RemoveField(
            model_name="user",
            name="bank_name",
        ),
        migrations.AddField(
            model_name="printer",
            name="account_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="printer",
            name="account_number",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="printer",
            name="bank_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="onetimepassword",
            name="otp",
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
