# Generated by Django 4.2.7 on 2024-08-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "authentication",
            "0008_remove_user_account_name_remove_user_account_number_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="printer",
            name="print_service_name",
            field=models.CharField(blank=True, max_length=225, unique=True),
        ),
    ]
